
package Vista;

/**
 *
 * @author asdw
 */
public class VentanaPrinciapl extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrinciapl.class.getName());

    /**
     * Creates new form VentanaPrinciapl
     */
    public VentanaPrinciapl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        PanelHabitaciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHabitacionesOcupadas = new javax.swing.JTable();
        LblHabitacionDisponible = new javax.swing.JLabel();
        LblHabitacionOcupada = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHabitacionesDisponibles = new javax.swing.JTable();
        PanelAnularReserva = new javax.swing.JPanel();
        LblCheckCedulaAnular = new javax.swing.JLabel();
        TxtBuscarCedulaAnular = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        LblCheckNombre4 = new javax.swing.JLabel();
        PanelCheckin = new javax.swing.JPanel();
        LblCheckNombre = new javax.swing.JLabel();
        LblCheckApellido = new javax.swing.JLabel();
        LblCheckCedula = new javax.swing.JLabel();
        LblCheckTelefono = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        BtnCheckin = new javax.swing.JButton();
        LblCheckHabitacion = new javax.swing.JLabel();
        CmboxHabitaciones = new javax.swing.JComboBox<>();
        BtnLimpiarCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(600, 500));

        TablaHabitacionesOcupadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitacion", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaHabitacionesOcupadas);

        LblHabitacionDisponible.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblHabitacionDisponible.setText("Habitaciones disponibles");

        LblHabitacionOcupada.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblHabitacionOcupada.setText("Habitaciones ocupadas");

        TablaHabitacionesDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaHabitacionesDisponibles);

        javax.swing.GroupLayout PanelHabitacionesLayout = new javax.swing.GroupLayout(PanelHabitaciones);
        PanelHabitaciones.setLayout(PanelHabitacionesLayout);
        PanelHabitacionesLayout.setHorizontalGroup(
            PanelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHabitacionesLayout.createSequentialGroup()
                .addComponent(LblHabitacionDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(LblHabitacionOcupada)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHabitacionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(PanelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHabitacionesLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(382, Short.MAX_VALUE)))
        );
        PanelHabitacionesLayout.setVerticalGroup(
            PanelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHabitacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHabitacionDisponible)
                    .addComponent(LblHabitacionOcupada))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(PanelHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelHabitacionesLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Habitaciones", PanelHabitaciones);

        LblCheckCedulaAnular.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckCedulaAnular.setText("Cedula");

        TxtBuscarCedulaAnular.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Anular reserva");

        LblCheckNombre4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckNombre4.setText("Escriba su cedula para anular su reserva");

        javax.swing.GroupLayout PanelAnularReservaLayout = new javax.swing.GroupLayout(PanelAnularReserva);
        PanelAnularReserva.setLayout(PanelAnularReservaLayout);
        PanelAnularReservaLayout.setHorizontalGroup(
            PanelAnularReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnularReservaLayout.createSequentialGroup()
                .addGroup(PanelAnularReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAnularReservaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelAnularReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCheckNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAnularReservaLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(LblCheckCedulaAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtBuscarCedulaAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelAnularReservaLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton2)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        PanelAnularReservaLayout.setVerticalGroup(
            PanelAnularReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnularReservaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LblCheckNombre4)
                .addGap(52, 52, 52)
                .addGroup(PanelAnularReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCheckCedulaAnular)
                    .addComponent(TxtBuscarCedulaAnular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Anular reserva", PanelAnularReserva);

        LblCheckNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckNombre.setText("Nombre");

        LblCheckApellido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckApellido.setText("Apellido");

        LblCheckCedula.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckCedula.setText("Cedula");

        LblCheckTelefono.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckTelefono.setText("Telefono");

        TxtNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        TxtApellido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        TxtCedula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        TxtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        BtnCheckin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCheckin.setText("Check-in");

        LblCheckHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblCheckHabitacion.setText("Habitacion");

        CmboxHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnLimpiarCampos.setText("Limpiar campos");

        javax.swing.GroupLayout PanelCheckinLayout = new javax.swing.GroupLayout(PanelCheckin);
        PanelCheckin.setLayout(PanelCheckinLayout);
        PanelCheckinLayout.setHorizontalGroup(
            PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCheckinLayout.createSequentialGroup()
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCheckinLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelCheckinLayout.createSequentialGroup()
                                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCheckNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblCheckApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblCheckCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblCheckTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCheckinLayout.createSequentialGroup()
                                .addComponent(LblCheckHabitacion)
                                .addGap(18, 18, 18)
                                .addComponent(CmboxHabitaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PanelCheckinLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnLimpiarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        PanelCheckinLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LblCheckApellido, LblCheckCedula, LblCheckNombre, LblCheckTelefono});

        PanelCheckinLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtApellido, TxtCedula, TxtNombre, TxtTelefono});

        PanelCheckinLayout.setVerticalGroup(
            PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCheckinLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCheckNombre)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCheckApellido)
                    .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCheckCedula)
                    .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCheckTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCheckHabitacion)
                    .addComponent(CmboxHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelCheckinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanelCheckinLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LblCheckApellido, LblCheckCedula, LblCheckNombre, LblCheckTelefono});

        PanelCheckinLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TxtApellido, TxtCedula, TxtNombre, TxtTelefono});

        jTabbedPane2.addTab("Check-in", PanelCheckin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrinciapl().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCheckin;
    public javax.swing.JButton BtnLimpiarCampos;
    public javax.swing.JComboBox<String> CmboxHabitaciones;
    public javax.swing.JLabel LblCheckApellido;
    public javax.swing.JLabel LblCheckCedula;
    public javax.swing.JLabel LblCheckCedulaAnular;
    public javax.swing.JLabel LblCheckHabitacion;
    public javax.swing.JLabel LblCheckNombre;
    public javax.swing.JLabel LblCheckNombre4;
    public javax.swing.JLabel LblCheckTelefono;
    public javax.swing.JLabel LblHabitacionDisponible;
    public javax.swing.JLabel LblHabitacionOcupada;
    public javax.swing.JPanel PanelAnularReserva;
    public javax.swing.JPanel PanelCheckin;
    public javax.swing.JPanel PanelHabitaciones;
    public javax.swing.JTable TablaHabitacionesDisponibles;
    public javax.swing.JTable TablaHabitacionesOcupadas;
    public javax.swing.JTextField TxtApellido;
    public javax.swing.JTextField TxtBuscarCedulaAnular;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtTelefono;
    public javax.swing.JButton jButton2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
